config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :tools
  resources :sites
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static#home"
  resources :users
  resources :sessions, only: [:create]
  resources :registrations, only: [:create]
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
end

app/models/tool.rb
class Tool < ApplicationRecord
    has_many :logs
    has_many :sites
    has_many :sites, through: :logs, dependent: :destroy
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all

    render json: @tools.to_json(include: [:sites, :logs])
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    render json: @tool.to_json(include: [:sites, :logs])
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tool_params
      params.require(:tool).permit(:name, :make, :model, :serial, :image)
    end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_with(model: tool, local: true) do |form| %>
  <% if tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
        <% tool.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :serial %>
    <%= form.text_field :serial %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Make</th>
      <th>Model</th>
      <th>Serial</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td><%= tool.name %></td>
        <td><%= tool.make %></td>
        <td><%= tool.model %></td>
        <td><%= tool.serial %></td>
        <td><%= tool.image %></td>
        <td><%= link_to 'Show', tool %></td>
        <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
        <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<p>
  <strong>Make:</strong>
  <%= @tool.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @tool.model %>
</p>

<p>
  <strong>Serial:</strong>
  <%= @tool.serial %>
</p>

<p>
  <strong>Image:</strong>
  <%= @tool.image %>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>